### ISSUE TITLE
FFS does not work with Custom System Builder Character Sheets

### ISSUE THREAD

**Issue by mpathiuk** [xaukael/ffs#14]
I've set up a character sheet template with Custom system Builder, when I enable ffs, and set up a freeform sheet, it does not show me the custom system builder character sheet template, only the ffs one, they seem to be separate.

**Comment by xaukael** [comment]
From what I understand, the data for the actors is configured through the CSB templates. FFS may then be able to use that data once it was all configured, but if you have not even started building the data for the system yet, I would recommend going the Simple Worldbuilding instead because I know that can be made to work with FFS. Unless you have a particular need of something in CSB.

**Comment by mpathiuk** [comment]
Ah sorry perhaps I wasn't clear. I've followed the CSB documentation to make the character sheet templates and character sheets based on that, but when I then use FFS, it does not show me the custom system builder character sheet template, only the ffs one, they seem to be separate. Which means I have to manually go back and forth by using sheet type to see each one.

**Comment by xaukael** [comment]
Seems about right. FFS can be used to replace a sheet by setting it as a character sheet, but it can also be used as a supplemental sheet activated by a macro for instance. 

Perhaps you can explain what you are using FFS for since you still want the CSB sheet.

In terms of dragging items to the sheet, that will just create a content link to the item in the sidebar.

**Comment by mpathiuk** [comment]
AH ok, from watching all the tutorials it seems like the intended behaviour is that you can have the base character sheet open and FFS at the same time so you can drag and drop what you want. That's the main functionality I'm looking for.

**Comment by xaukael** [comment]
There are a few ways to utilize the module. It replacing the system's sheet came late in development and has caused confusion a few times.
