### ISSUE TITLE
Issue with Roll Formulas in the GURPS System

### ISSUE THREAD

**Issue by eKorbeau** [xaukael/ffs#15]
Hi,

I'm using the GURPS system, and I've encountered multiple issues related to rolls and formulas. Specifically:

- Rolls tied to attributes are not functioning as expected (e.g., I can't insert [ST] to make a Strength Roll).
- I am unable to insert formulas for any type of roll (e.g., I can't insert /roll 3d6, even when using double brackets as shown in the tutorial video).
- Some Formulas seem problematic. For instance, importing the Dodge value always displays 0, even though the attributes are correctly configured.

Is this a known issue? Are there any temporary fixes or updates in progress?

Thank you for your assistance and for the effort you’ve put into developing this module!

**Comment by xaukael** [comment]
There is some weird css stuff going on with the custom [ST] enrichment that I do not know how to resolve. It does the enrichment but it is impossible to click it because it is jumping around. There is nothing I can do about systems doing non-core stuff and I don't have the bandwidth to keep up with it all.

The roll formula [[/r 3d6]] seems to work on a fresh GURPS world in v12. So unless you are using different version, not sure what could be going on there.

The system is also doing a lot of non-core stuff with inline rolls that I cannot work around.
